font:
  normal:
    family: JetBrains Mono Nerd Font
    style: SemiBold

  bold:
    family: JetBrains Mono Nerd Font
    style: Bold

  italic:
    family: JetBrains Mono Nerd Font
    style: Italic

  bold_italic:
    family: JetBrains Mono Nerd Font
    style: Bold Italic

  size: 11.5

import:
  # uncomment the flavour you want below:
  - ~/.config/alacritty/catppuccin/catppuccin-mocha.yml
#  - ~/.config/alacritty/catppuccin/catppuccin-macchiato.yml
#  - ~/.config/alacritty/catppuccin/catppuccin-frappe.yml
#  - ~/.config/alacritty/catppuccin/catppuccin-latte.yml
